# AI Assignment 2: Neural Network

In [5]:
import numpy as np
from decimal import Decimal, ROUND_HALF_UP

In [2]:
def sigmoid(z):
    '''The sigmoid function'''
    return 1.0 / (1.0 + np.exp(-z))

def sigmoid_prime(z):
    '''Derivative of the sigmoid function'''
    return sigmoid(z) * (1-sigmoid(z))

In [3]:
def read_neural_net_file(nn_filename):
    with open(nn_filename) as f:
        line = f.readline()
        nums = [int(num) for num in line.split()]
        Ni, Nh, No = nums

        w1 = np.zeros([Nh, Ni+1])
        for i in range(Nh):
            line = f.readline()
            nums = [float(num) for num in line.split()]
            w1[i, :] = nums

        w2 = np.zeros([No, Nh+1])
        for i in range(No):
            line = f.readline()
            nums = [float(num) for num in line.split()]
            w2[i, :] = nums

    return Ni, Nh, No, [w1, w2]

In [4]:
def read_data_file(train_filename):
    with open(train_filename) as f:
        line = f.readline()
        nums = [int(num) for num in line.split()]
        num_obs, Ni, No = nums

        inputs = np.zeros([num_obs, Ni])
        outputs = np.zeros([num_obs, No])

        for i in range(num_obs):
            line = f.readline()
            nums = [float(num) for num in line.split()]
            inputs[i, :] = nums[:Ni]
            outputs[i, :] = nums[Ni:]
            
    return list(zip(inputs, outputs))

In [31]:
def train(self, training_data, learning_rate, epochs):
    for _ in range(epochs):
        for x, y in training_data:
            # Propagate inputs forward to compute outputs
            act = x
            acts = [x]
            zs = []
            for w in self.weights:
                z = (w @ act)
                zs.append(z)
                act = sigmoid(z)
                acts.append(act)
        
            # Propagate deltas backward from output layer to input layer
            nabla_b = [np.zeros(b.shape) for b in self.biases]
            nabla_w = [np.zeros(w.shape) for w in self.weights]            
            
            delta = sigmoid_prime(zs[-1]) * (y - acts[-1])

            # Update weights and biases using deltas
            self.weights = [w + learning_rate*nw
                            for w, nw in zip(self.weights, nabla_w)]
            self.biases = [b + learning_rate*nb
                           for b, nb in zip(self.biases, nabla_b)]

In [60]:
x, y = training_data[0]

In [66]:
[weights[i].shape for i in range(len(weights))]

[(5, 31), (1, 6)]

In [61]:
# Propagate inputs forward to compute outputs
act = np.insert(x, 0, -1)
acts = [x]
zs = []
for w in weights:
    z = np.dot(w, np.insert(act, 0, -1))
    zs.append(z)
    act = sigmoid(z)
    acts.append(act)

ValueError: shapes (5,31) and (32,) not aligned: 31 (dim 1) != 32 (dim 0)

In [62]:
act.shape

(31,)

In [63]:
w.shape

(5, 31)

In [ ]:
# Propagate deltas backward from output layer to input layer
nabla_b = [np.zeros(b.shape) for b in self.biases]
nabla_w = [np.zeros(w.shape) for w in self.weights]            

delta = sigmoid_prime(zs[-1]) * (y - acts[-1])

In [ ]:
# Update weights and biases using deltas
self.weights = [w + learning_rate*nw
                for w, nw in zip(self.weights, nabla_w)]
self.biases = [b + learning_rate*nb
               for b, nb in zip(self.biases, nabla_b)]

In [38]:
asdf = [1,2,3,4,5.1]

In [39]:
sum(asdf) / len(asdf)

3.02

In [9]:
confusion = np.ones([4, 2, 2])

In [33]:
confusion[0]

array([[ 1.,  2.],
       [ 3.,  4.]])

In [32]:
confusion.sum(axis=0)

array([[ 4.,  5.],
       [ 6.,  7.]])

In [27]:
np.append(confusion[0].flatten(), [1, 2])

array([ 1.,  2.,  3.,  4.,  1.,  2.])

In [7]:
nn.read_data_file('tests/grades_train.txt')

[(array([ 0.6 ,  0.51,  0.66,  0.63,  0.68]), array([ 1.,  0.,  0.,  0.])),
 (array([ 0.82,  0.97,  0.89,  0.8 ,  0.85]), array([ 1.,  1.,  1.,  0.])),
 (array([ 0.89,  0.98,  0.81,  0.92,  0.82]), array([ 1.,  1.,  1.,  0.])),
 (array([ 1.  ,  0.85,  0.8 ,  0.86,  0.91]), array([ 1.,  1.,  1.,  0.])),
 (array([ 0.83,  0.97,  0.94,  0.84,  0.8 ]), array([ 1.,  1.,  1.,  0.])),
 (array([ 0.79,  0.87,  0.64,  0.79,  0.88]), array([ 1.,  1.,  0.,  0.])),
 (array([ 0.81,  0.95,  0.94,  0.85,  0.97]), array([ 1.,  1.,  1.,  1.])),
 (array([ 0.75,  0.98,  0.58,  0.75,  0.59]), array([ 1.,  1.,  0.,  0.])),
 (array([ 0.87,  0.91,  0.95,  0.88,  0.98]), array([ 1.,  1.,  1.,  1.])),
 (array([ 0.91,  0.97,  0.99,  0.99,  0.85]), array([ 1.,  1.,  1.,  1.])),
 (array([ 0.74,  0.69,  0.9 ,  0.78,  0.99]), array([ 1.,  1.,  1.,  0.])),
 (array([ 0.57,  0.68,  0.72,  0.59,  0.74]), array([ 1.,  0.,  0.,  0.])),
 (array([ 0.67,  0.84,  0.67,  0.7 ,  0.5 ]), array([ 1.,  0.,  0.,  0.])),
 (array([ 0.